import { Command } from 'commander';
export declare const alkanesTrace: Command;
export declare const alkaneContractDeploy: Command;
export declare const alkaneTokenDeploy: Command;
export declare const alkaneExecute: Command;
export declare const alkaneBurn: Command;
export declare const alkaneSwap: Command;
export declare const alkaneSplit: Command;
export declare const alkaneSend: Command;
export declare const alkaneCreatePool: Command;
export declare const alkaneMint: Command;
export declare const alkaneSimulate: Command;
